### ISSUE TITLE
How to get the latest data.json?

### ISSUE THREAD

**Issue by rajiteh** [kaveenr/sl-protest-tracker#1]
Hey @kaveenr , 

A friend of mine showed me this repo and I think it's a great initiative, and I would like to contribute to it. However, I'm having trouble setting up the repo. Is there any way to retrieve the `data.json` from the currently deployed version or do I have to figure out my own Google API keys to generate the json from the sheet?

Also if you've got any feature ideas that needs to be worked on let me know!

Thx!

**Comment by kaveenr** [comment]
Thanks @rajiteh.

You can run this on the root of the project for now.

```sh
curl https://protests.projects.ukr.lk/\?from\=2022-04-09\&_data\=routes%2Findex | jq .dataset > app/assets/data.json
```
